# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PasswordCli < Formula
  desc ""
  homepage "https://github.com/Anirudh12345678/PwdCLI"
  version "0.1"

  on_macos do
    url "https://github.com/Anirudh12345678/PwdCLI/releases/download/v0.1/name_0.1_darwin_amd64.tar.gz"
    sha256 "e05594aa4c5d745da3782df5f4a57435550a991d423a2c65a4200c0978643eeb"

    def install
      bin.install "bin/name"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the PasswordCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Anirudh12345678/PwdCLI/releases/download/v0.1/name_0.1_linux_amd64.tar.gz"
        sha256 "6ce8baf392081b7630cb58014a4f03835052cd0a122232f8ac09b7b0a8189be7"

        def install
          bin.install "bin/name"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Anirudh12345678/PwdCLI/releases/download/v0.1/name_0.1_linux_armv6.tar.gz"
        sha256 "e19ea5f8226a88729432037ad9d3cf8c44bbb3a82775f5d14900a435b5065b3f"

        def install
          bin.install "bin/name"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Anirudh12345678/PwdCLI/releases/download/v0.1/name_0.1_linux_arm64.tar.gz"
        sha256 "395ce85b98e8999ae0d54b34e4f4011f202df7404a425e34a18518479d1158ea"

        def install
          bin.install "bin/name"
        end
      end
    end
  end
end
